politifact:
  split: public
  split_repeat: 5
  epochs: 200
  eval_every: 1
  early_stop: 50
  batch_size: 64
  lr: 0.0001
  dropout: 0.3
  weight_decay: 0.001
  scheduler: cosine
  warmup_steps: 50
  eta_min: 0.000001
  opt_beta1: 0.95
  opt_beta2: 0.999
  grad_clip: 1.0
  hidden_dim: 512
  heads: 8
  num_layers: 2
  pattern_encoder: transformer
  pattern_encoder_layers: 4
  pattern_encoder_heads: 2
  pre_sample_pattern_num: 256
  pre_sample_batch_size: 1024
  num_patterns: 32
  time_gamma: 2.5
  cluster_ratio: 0.2
  pattern_size: 4
  multiscale: [2, 4, 6, 8]
  p: 4
  q: 0.5
  node_pe: none
  pe_encoder: mean
  node_pe_dim: 8
  pe_weight: 0.1
  use_attn_fusion: True
  use_cls_token: True
gossipcop:
  split: public
  split_repeat: 5
  epochs: 300
  eval_every: 1
  early_stop: 40
  batch_size: 128
  lr: 0.0005
  dropout: 0.4
  weight_decay: 0.0005
  scheduler: cosine
  warmup_steps: 50
  eta_min: 0.000001
  grad_clip: 2.0
  hidden_dim: 128
  heads: 2
  num_layers: 2
  pattern_encoder: transformer
  pattern_encoder_layers: 2
  pattern_encoder_heads: 2
  pre_sample_pattern_num: 256
  pre_sample_batch_size: 4096
  num_patterns: 16
  pattern_size: 12
  multiscale: [1, 2, 3, 4]
  p: 4
  q: 1
  node_pe: none
  pe_encoder: mean
  node_pe_dim: 8
  pe_weight: 0.1
  use_attn_fusion: True
  use_cls_token: True
imdb-b:
  split: public
  batch_size: 1024
  lr: 0.001
  dropout: 0.1
  weight_decay: 0.0
  node_pe: rw
  pe_encoder: mean
  node_pe_dim: 8
  pe_weight: 0.1
  p: 1
  q: 0.1
  use_attn_fusion: False
  use_cls_token: False