graph:
  politifact:
    split: public
    split_repeat: 5
    epochs: 300
    eval_every: 1
    early_stop: 40
    batch_size: 32
    lr: 0.0005
    dropout: 0.5
    weight_decay: 0.0005
    scheduler: cosine
    warmup_steps: 50
    eta_min: 0.000001
    label_smoothing: 0.0
    grad_clip: 2.0
    hidden_dim: 128
    heads: 2
    num_layers: 2
    pattern_encoder: transformer
    pattern_encoder_layers: 2
    pattern_encoder_heads: 2
    pre_sample_pattern_num: 256
    pre_sample_batch_size: 4096
    num_patterns: 16
    pattern_size: 4
    multiscale: [1, 2, 3, 4]
    p: 4
    q: 1
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 8
    pe_weight: 0.1
    use_attn_fusion: True
    use_cls_token: True
  gossipcop:
    split: public
    split_repeat: 5
    epochs: 300
    eval_every: 1
    early_stop: 40
    batch_size: 64
    lr: 0.0005
    dropout: 0.4
    weight_decay: 0.0005
    scheduler: cosine
    warmup_steps: 50
    eta_min: 0.000001
    label_smoothing: 0.0
    grad_clip: 2.0
    hidden_dim: 128
    heads: 2
    num_layers: 2
    pattern_encoder: transformer
    pattern_encoder_layers: 2
    pattern_encoder_heads: 2
    pre_sample_pattern_num: 256
    pre_sample_batch_size: 4096
    num_patterns: 16
    pattern_size: 4
    multiscale: [1, 2, 3, 4]
    p: 4
    q: 1
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 8
    pe_weight: 0.1
    use_attn_fusion: True
    use_cls_token: True
  bbbp:
    split: public
    batch_size: 1024
  imdb-b:
    split: public
    batch_size: 1024
    lr: 0.001
    dropout: 0.1
    weight_decay: 0.0
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 8
    pe_weight: 0.1
    p: 1
    q: 0.1
    use_attn_fusion: False
    use_cls_token: False
  imdb-m:
    split: public
    batch_size: 1024
    lr: 0.01
    dropout: 0.3
    weight_decay: 0.01
    node_pe: rw
    pe_encoder: gru
    node_pe_dim: 16
    pe_weight: 0.1
    p: 1
    q: 10
    use_attn_fusion: False
    use_cls_token: False
  collab:
    split: public
    batch_size: 1024
    lr: 0.01
    dropout: 0.1
    weight_decay: 0.0
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 4
    pe_weight: 0.1
    p: 10
    q: 10
    use_attn_fusion: False
    use_cls_token: False
  reddit-b:
    split: public
    batch_size: 1024
    lr: 0.01
    dropout: 0.3
    weight_decay: 0.0
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 8
    pe_weight: 1
    p: 0.1
    q: 10
    use_attn_fusion: False
    use_cls_token: False
  reddit-m5k:
    split: public
    batch_size: 1024
    lr: 0.001
    dropout: 0.1
    weight_decay: 0.0
    node_pe: rw
    pe_encoder: mean
    node_pe_dim: 8
    pe_weight: 0.1
    p: 1
    q: 1
    use_attn_fusion: False
    use_cls_token: True
  reddit-m12k:
    split: public
    batch_size: 256
    lr: 0.005
    dropout: 0.1
    weight_decay: 0.01
    node_pe: rw
    pe_encoder: gru
    node_pe_dim: 8
    pe_weight: 0.1
    p: 1
    q: 1
    use_attn_fusion: False
    use_cls_token: False
  zinc:
    split: public
    batch_size: 1024
    lr: 0.01
    dropout: 0.1
    weight_decay: 0.0
    node_pe: rw
    node_pe_dim: 8
    pe_encoder: gru
    pe_weight: 1.0
    p: 1
    q: 1
    use_attn_fusion: False
    use_cls_token: False
  zinc_full:
    split: public
    batch_size: 1024
    lr: 0.01
    dropout: 0.1
    weight_decay: 0.0
    node_pe: rw
    node_pe_dim: 8
    pe_encoder: gru
    pe_weight: 1.0
    p: 1
    q: 1
    use_attn_fusion: False
    use_cls_token: False
